### ISSUE TITLE
[bug] Unexpected convertion result when containing a letter "}" in content property

### ISSUE THREAD

**Issue by mtripg6666tdr** [mtripg6666tdr/css-vh-replace-loader#1]
same as title

About CSS files which contain a letter "}" in content property like this:
```css
html:after {
  content: "}";
  width: 20vh;
}
```
will be expected to be converted into one like this:
```css
html:after {
  content: "}";
  width: 20vh;
  width: calc(var(--vh,1vh)*20);
}
```
however actually that will be like this:
```css
html:after {
  content: "}";
  width: 20vh;
}
```
